//! Replays recorded market logs through the package on top of a snapshot and checks the book
//! against on-chain reads.
//!
//! The fixture is generated by the ignored `test_generate_kuru_replay_fixture` test in
//! `tycho-indexer` (`extractor/bootstrap/kuru.rs`): the state of some markets at a block N as the
//! bootstrap snapshot reads it, the `map_snapshot` parameters the indexer builds from it, every
//! log of the markets over N+1..=N+k, and the snapshot at N+k. The stores start from the
//! parameters only, as a stream started at N+1 does; the output is applied the way the indexer
//! resolves deltas, and the levels (`a/`, `b/`) and resting orders (`o/`) must equal the chain's
//! at N+k exactly. Vault, fee and state attributes come from storage writes, which logs do not
//! carry, so they are not compared.

use std::collections::{BTreeMap, HashMap};

use serde::Deserialize;
use substreams::scalar::BigInt;
use substreams_ethereum::pb::eth::v2::{Log, TransactionTrace};

use super::*;

#[derive(Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    start_block: u64,
    snapshot_params: String,
    start: HashMap<String, State>,
    logs: Vec<FixtureLog>,
    end: HashMap<String, State>,
}

#[derive(Deserialize, Default)]
struct State {
    attributes: BTreeMap<String, String>,
    balances: BTreeMap<String, String>,
}

#[derive(Deserialize)]
struct FixtureLog {
    block_number: u64,
    transaction_hash: String,
    transaction_index: u32,
    log_index: u32,
    address: String,
    topics: Vec<String>,
    data: String,
}

fn unhex(value: &str) -> Vec<u8> {
    hex::decode(value.trim_start_matches("0x")).expect("fixture hex")
}

/// The book part of a market's state: levels and orders by name, balances by token.
#[derive(Default, Debug, PartialEq)]
struct Book {
    attributes: BTreeMap<String, BigInt>,
    balances: BTreeMap<Vec<u8>, BigInt>,
}

fn is_book(name: &str) -> bool {
    ["a/", "b/", "o/"]
        .iter()
        .any(|p| name.starts_with(p))
}

impl Book {
    fn from_state(state: &State) -> Self {
        Self {
            attributes: state
                .attributes
                .iter()
                .filter(|(name, _)| is_book(name))
                .map(|(name, value)| (name.clone(), BigInt::from_unsigned_bytes_be(&unhex(value))))
                .filter(|(_, value)| !value.is_zero())
                .collect(),
            balances: state
                .balances
                .iter()
                .map(|(token, value)| (unhex(token), BigInt::from_unsigned_bytes_be(&unhex(value))))
                .collect(),
        }
    }

    fn apply(&mut self, entity: &EntityChanges) {
        for attr in entity
            .attributes
            .iter()
            .filter(|a| is_book(&a.name))
        {
            let current = self
                .attributes
                .entry(attr.name.clone())
                .or_insert_with(BigInt::zero);
            *current = match attr.change() {
                ChangeType::Delta => current.clone() + BigInt::from_signed_bytes_be(&attr.value),
                ChangeType::Update | ChangeType::Creation => {
                    BigInt::from_unsigned_bytes_be(&attr.value)
                }
                ChangeType::Deletion => BigInt::zero(),
                ChangeType::Unspecified => panic!("unspecified change on {}", attr.name),
            };
        }
        self.attributes
            .retain(|_, value| !value.is_zero());
    }
}

#[test]
fn test_replay_matches_chain() {
    let fixture: Fixture =
        serde_json::from_str(include_str!("../tests/fixtures/replay.json")).unwrap();
    for case in &fixture.cases {
        run_case(case);
    }
}

fn run_case(case: &Case) {
    // Stores start from the snapshot parameters alone.
    let seed = snapshot(&case.snapshot_params, case.start_block + 1).unwrap();
    assert!(snapshot(&case.snapshot_params, case.start_block)
        .unwrap()
        .markets
        .is_empty());
    let markets: HashMap<String, String> = seed
        .markets
        .iter()
        .map(|m| (m.market.clone(), m.params.clone()))
        .collect();
    assert_eq!(markets.len(), case.start.len(), "every market is seeded");
    let mut sizes: HashMap<String, u128> = HashMap::new();
    let mut meta: HashMap<String, String> = HashMap::new();
    for o in &seed.orders {
        sizes.insert(key_of(&o.market, o.id), u(&o.size));
        meta.insert(key_of(&o.market, o.id), format!("{}:{}", o.price, o.is_buy));
    }

    let mut books: HashMap<String, Book> = case
        .start
        .iter()
        .map(|(market, state)| (market.clone(), Book::from_state(state)))
        .collect();

    let mut blocks: BTreeMap<u64, Vec<&FixtureLog>> = BTreeMap::new();
    for log in &case.logs {
        blocks
            .entry(log.block_number)
            .or_default()
            .push(log);
    }
    let (mut events_seen, mut orders_seen) = (0, 0);
    for (_, mut logs) in blocks {
        logs.sort_by_key(|log| log.log_index);
        let events: Vec<Event> = logs
            .iter()
            .filter_map(|log| {
                let eth_log = Log {
                    address: unhex(&log.address),
                    topics: log
                        .topics
                        .iter()
                        .map(|t| unhex(t))
                        .collect(),
                    data: unhex(&log.data),
                    index: log.log_index,
                    block_index: log.log_index,
                    // ordinal 0 is the snapshot's
                    ordinal: u64::from(log.log_index) + 1,
                };
                let tx = TransactionTrace {
                    hash: unhex(&log.transaction_hash),
                    index: log.transaction_index,
                    ..Default::default()
                };
                log_event(&eth_log, log.address.to_lowercase(), &tx)
            })
            .collect();
        // One event at a time, so the stores answer as of just before it.
        let mut out = LevelDeltas::default();
        for e in events {
            events_seen += 1;
            let one = level_deltas(
                &Events { events: vec![e.clone()] },
                |key, _| sizes.get(key).copied().unwrap_or(0),
                |key, _| meta.get(key).cloned(),
                |market| Market::decode(&markets[market]).pp,
            )
            .unwrap_or_else(|err| panic!("block {}: {err}", logs[0].block_number));
            match book_event(&e).order_size() {
                Some((_, 0)) => {
                    sizes.remove(&order_key(&e));
                    meta.remove(&order_key(&e));
                }
                Some((_, size)) => {
                    sizes.insert(order_key(&e), size);
                    if e.kind == 0 {
                        meta.entry(order_key(&e))
                            .or_insert_with(|| format!("{}:{}", e.price, e.is_buy));
                    }
                }
                None => {}
            }
            orders_seen += one.orders.len();
            out.deltas.extend(one.deltas);
            out.orders.extend(one.orders);
        }
        let balances = balance_deltas(&out, |market| Market::decode(&markets[market]));
        let mut txs = HashMap::new();
        add_book_changes(&mut txs, out, balances);
        let mut txs: Vec<_> = txs
            .into_values()
            .filter_map(|b| b.build())
            .collect();
        txs.sort_by_key(|c| c.tx.as_ref().map(|t| t.index));
        for tx in txs {
            for entity in &tx.entity_changes {
                books
                    .entry(entity.component_id.clone())
                    .or_default()
                    .apply(entity);
            }
            for change in &tx.balance_changes {
                assert_eq!(change.change(), ChangeType::Delta);
                let current = books
                    .entry(String::from_utf8(change.component_id.clone()).unwrap())
                    .or_default()
                    .balances
                    .entry(change.token.clone())
                    .or_insert_with(BigInt::zero);
                *current = current.clone() + BigInt::from_signed_bytes_be(&change.balance);
            }
        }
    }
    assert!(events_seen > 0 && orders_seen > 0, "fixture replays no order events");

    for (market, expected) in &case.end {
        let got = books.remove(market).unwrap_or_default();
        let expected = Book::from_state(expected);
        assert_eq!(got.attributes, expected.attributes, "market {market}");
        // Balances convert each level delta with integer division, the chain read converts each
        // level whole: they may differ by rounding, one unit per event at most.
        for (token, want) in &expected.balances {
            let have = got
                .balances
                .get(token)
                .cloned()
                .unwrap_or_default();
            let diff = (want.clone() - have.clone()).to_string();
            let diff: i128 = diff.parse().unwrap();
            assert!(
                diff.unsigned_abs() <= events_seen as u128,
                "market {market} token {}: chain {want}, replay {have}",
                hex::encode(token)
            );
        }
    }
}
