//! Replays recorded pool logs through the package and checks the indexed state against on-chain
//! reads.
//!
//! The fixture is generated by the ignored `test_generate_uniswap_v3_replay_fixture` test in
//! `tycho-indexer` (`extractor/bootstrap/uniswap_v3.rs`) with `LAYOUT=pancakeswap`. It holds, per case, the state of some
//! pools at a start block as the bootstrap snapshot reads it, every log the pools emitted up to an
//! end block, and the snapshot read at the end block. Each case starts from its start state with
//! empty stores, as a stream started after a bootstrap does, applies the package output the way
//! the indexer resolves deltas, and must reproduce the end state exactly.

use std::collections::{BTreeMap, HashMap};

use serde::Deserialize;
use substreams::scalar::BigInt;
use substreams_ethereum::pb::eth::v2::{Log, TransactionTrace};
use tycho_substreams::prelude::*;

use super::{
    map_balance_changes::event_to_balance_deltas,
    map_events::log_to_event,
    map_protocol_changes::{transaction_changes, Params},
    map_snapshot::snapshot_pools,
    map_store_liquidity::{event_to_current_tick, liquidity_changes},
    map_ticks::event_to_ticks_deltas,
};
use crate::pb::pancakeswap::v3::{events::PoolEvent, Events, Pool, TickDeltas};

#[derive(Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    /// The snapshot block. The stream starts at the next block.
    start_block: u64,
    /// The `map_snapshot` parameters the indexer passes, empty for a replay from deployment.
    snapshot_params: String,
    pools: Vec<FixturePool>,
    start: HashMap<String, State>,
    logs: Vec<FixtureLog>,
    end: HashMap<String, State>,
}

#[derive(Deserialize)]
struct FixturePool {
    address: String,
    token0: String,
    token1: String,
    fee: u64,
}

#[derive(Deserialize, Clone, Default, Debug, PartialEq)]
struct State {
    attributes: BTreeMap<String, String>,
    balances: BTreeMap<String, String>,
}

#[derive(Deserialize)]
struct FixtureLog {
    block_number: u64,
    transaction_hash: String,
    transaction_index: u32,
    log_index: u32,
    address: String,
    topics: Vec<String>,
    data: String,
}

fn unhex(value: &str) -> Vec<u8> {
    hex::decode(value.trim_start_matches("0x")).expect("fixture hex")
}

/// Pool state with every value decoded, a missing value counting as zero.
#[derive(Default, Debug, PartialEq)]
struct Values {
    attributes: BTreeMap<String, BigInt>,
    balances: BTreeMap<Vec<u8>, BigInt>,
}

impl Values {
    fn from_state(state: &State) -> Self {
        Self {
            attributes: state
                .attributes
                .iter()
                .map(|(name, value)| (name.clone(), BigInt::from_signed_bytes_be(&unhex(value))))
                .filter(|(_, value)| !value.is_zero())
                .collect(),
            balances: state
                .balances
                .iter()
                .map(|(token, value)| (unhex(token), BigInt::from_unsigned_bytes_be(&unhex(value))))
                .collect(),
        }
    }

    /// Applies one transaction's output as the indexer resolves it.
    fn apply(&mut self, entity: &EntityChanges) {
        for attr in &entity.attributes {
            let value = BigInt::from_signed_bytes_be(&attr.value);
            let current = self
                .attributes
                .entry(attr.name.clone())
                .or_insert_with(BigInt::zero);
            match attr.change() {
                ChangeType::Delta => *current = current.clone() + value,
                ChangeType::Update | ChangeType::Creation => *current = value,
                ChangeType::Deletion => *current = BigInt::zero(),
                ChangeType::Unspecified => panic!("unspecified change on {}", attr.name),
            }
        }
        self.attributes
            .retain(|_, value| !value.is_zero());
    }

    fn apply_balance(&mut self, change: &BalanceChange) {
        let current = self
            .balances
            .entry(change.token.clone())
            .or_insert_with(BigInt::zero);
        *current = if change.change() == ChangeType::Delta {
            current.clone() + BigInt::from_signed_bytes_be(&change.balance)
        } else {
            BigInt::from_unsigned_bytes_be(&change.balance)
        };
    }
}

fn run_case(case: &Case) {
    // The stores start from the snapshot the indexer passes; pools created in the stream would
    // come from `map_pools_created`, which a replay from deployment emulates with the fixture list.
    let snapshot = snapshot_pools(&case.snapshot_params, case.start_block + 1).unwrap();
    let mut pools: HashMap<Vec<u8>, Pool> = HashMap::new();
    let mut current_ticks: HashMap<String, i64> = HashMap::new();
    for seeded in snapshot.pools {
        let pool = seeded.pool.unwrap();
        current_ticks.insert(hex::encode(&pool.address), seeded.tick.into());
        pools.insert(pool.address.clone(), pool);
    }
    if case.snapshot_params.is_empty() {
        for p in &case.pools {
            let address = unhex(&p.address);
            let pool = Pool {
                address: address.clone(),
                token0: unhex(&p.token0),
                token1: unhex(&p.token1),
                fee: p.fee,
                created_tx_hash: vec![],
            };
            pools.insert(address, pool);
        }
    }
    assert_eq!(pools.len(), case.pools.len(), "case {}: snapshot pools", case.name);
    let mut state: HashMap<String, Values> = case
        .start
        .iter()
        .map(|(pool, state)| (pool.clone(), Values::from_state(state)))
        .collect();

    let mut blocks: BTreeMap<u64, Vec<&FixtureLog>> = BTreeMap::new();
    for log in &case.logs {
        blocks
            .entry(log.block_number)
            .or_default()
            .push(log);
    }
    for (_, mut logs) in blocks {
        logs.sort_by_key(|log| log.log_index);
        let pool_events: Vec<PoolEvent> = logs
            .iter()
            .filter_map(|log| {
                let address = unhex(&log.address);
                let eth_log = Log {
                    address: address.clone(),
                    topics: log
                        .topics
                        .iter()
                        .map(|t| unhex(t))
                        .collect(),
                    data: unhex(&log.data),
                    index: log.log_index,
                    block_index: log.log_index,
                    ordinal: u64::from(log.log_index),
                };
                let tx = TransactionTrace {
                    hash: unhex(&log.transaction_hash),
                    index: log.transaction_index,
                    ..Default::default()
                };
                log_to_event(&eth_log, pools[&address].clone(), &tx)
            })
            .collect();

        // The tick store answers with the tick set by an earlier event of the stream.
        let mut tick_before: HashMap<u64, Option<i64>> = HashMap::new();
        for event in &pool_events {
            tick_before.insert(
                event.log_ordinal,
                current_ticks
                    .get(&event.pool_address)
                    .copied(),
            );
            if let Some((pool, _, tick)) = event_to_current_tick(event.clone()) {
                current_ticks.insert(pool, tick.into());
            }
        }
        let events = Events { pool_events };
        let liquidity =
            liquidity_changes(events.clone(), |event| tick_before[&event.log_ordinal]).unwrap();
        let changes = transaction_changes(
            &Params::default(),
            BlockChanges::default(),
            events.clone(),
            BlockBalanceDeltas {
                balance_deltas: events
                    .pool_events
                    .iter()
                    .cloned()
                    .flat_map(event_to_balance_deltas)
                    .collect(),
            },
            TickDeltas {
                deltas: events
                    .pool_events
                    .iter()
                    .cloned()
                    .flat_map(event_to_ticks_deltas)
                    .collect(),
            },
            liquidity,
        );
        for tx in changes {
            for entity in &tx.entity_changes {
                state
                    .entry(entity.component_id.clone())
                    .or_default()
                    .apply(entity);
            }
            for balance in &tx.balance_changes {
                state
                    .entry(String::from_utf8(balance.component_id.clone()).unwrap())
                    .or_default()
                    .apply_balance(balance);
            }
        }
    }

    // Attributes must match exactly. Balances come from events, so tokens sent to a pool
    // without a pool event leave `balanceOf` above them; the difference must be tiny.
    for (pool, expected) in &case.end {
        let got = state.remove(pool).unwrap_or_default();
        let expected = Values::from_state(expected);
        assert_eq!(got.attributes, expected.attributes, "case {}: pool {pool}", case.name);
        for (token, want) in &expected.balances {
            let have = got
                .balances
                .get(token)
                .cloned()
                .unwrap_or_default();
            let diff = want.clone() - have;
            assert!(
                diff >= BigInt::zero() && diff <= BigInt::from(1_000),
                "case {}: pool {pool} token {}: chain {want}, events {diff} lower",
                case.name,
                hex::encode(token)
            );
        }
    }
}

#[test]
fn test_replay_matches_chain() {
    let fixture: Fixture =
        serde_json::from_str(include_str!("../../tests/fixtures/replay.json")).unwrap();
    let names: Vec<&str> = fixture
        .cases
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(names, ["bootstrap", "replay"]);
    for case in &fixture.cases {
        run_case(case);
    }
}

#[test]
fn test_tick_deltas_sum_to_absolute_liquidity() {
    let mint = |lower: i32, upper: i32, amount: &str| PoolEvent {
        log_ordinal: 0,
        pool_address: "aa".to_string(),
        token0: "01".to_string(),
        token1: "02".to_string(),
        fee: 500,
        transaction: Some(Default::default()),
        r#type: Some(crate::pb::pancakeswap::v3::events::pool_event::Type::Mint(
            crate::pb::pancakeswap::v3::events::pool_event::Mint {
                owner: String::new(),
                sender: String::new(),
                tick_lower: lower,
                tick_upper: upper,
                amount: amount.to_string(),
                amount_0: "1".to_string(),
                amount_1: "1".to_string(),
            },
        )),
    };
    let mut values = Values::default();
    for event in [mint(-10, 10, "100"), mint(0, 10, "7"), mint(-10, 0, "3")] {
        let changes = transaction_changes(
            &Params::default(),
            BlockChanges::default(),
            Events::default(),
            BlockBalanceDeltas::default(),
            TickDeltas { deltas: event_to_ticks_deltas(event) },
            Default::default(),
        );
        for tx in changes {
            for entity in &tx.entity_changes {
                values.apply(entity);
            }
        }
    }
    let tick = |t: i32| values.attributes[&format!("ticks/{t}/net-liquidity")].clone();
    // Additive stores held the running sum from zero: 100 + 3 at -10, 7 - 3 at 0, -100 - 7 at 10.
    assert_eq!(
        (tick(-10), tick(0), tick(10)),
        (BigInt::from(103), BigInt::from(4), BigInt::from(-107))
    );
}
