//! Replays recorded PoolManager logs through the package and checks the indexed state against
//! on-chain reads.
//!
//! The fixture is generated by the ignored `test_generate_uniswap_v4_replay_fixture` test in
//! `tycho-indexer` (`extractor/bootstrap/uniswap_v4.rs`). It holds, per case, the state of some
//! pools at a start block as the bootstrap snapshot reads it, every log of those pools up to an
//! end block, and the `StateView` reads at the end block. Each case starts from its start state
//! with empty stores, as a stream started after a bootstrap does, applies the package output the
//! way the indexer resolves deltas, and must reproduce the end state's attributes exactly.
//! Balances are not compared: see `UniswapV4Source::expected_state`.

use std::collections::{BTreeMap, HashMap};

use serde::Deserialize;
use substreams::scalar::BigInt;
use substreams_ethereum::pb::eth::v2::{Log, TransactionTrace};
use tycho_substreams::prelude::*;

use super::{
    map_events::log_to_event, map_snapshot::snapshot_pools,
    map_store_balance_changes::balance_changes, map_store_liquidity::liquidity_changes,
    map_store_ticks::event_to_ticks_deltas, store_current_sqrtprice::event_to_current_sqrt_price,
    store_current_tick::event_to_current_tick,
};
use crate::{
    pb::uniswap::v4::{events::PoolEvent, Events, Pool, TickDeltas},
    utils::protocol_changes::collect_transaction_changes,
};

#[derive(Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    /// The snapshot block. The stream starts at the next block.
    start_block: u64,
    /// The `map_snapshot_0` parameters the indexer passes, empty for a replay from creation.
    snapshot_params: String,
    pools: Vec<FixturePool>,
    start: HashMap<String, State>,
    logs: Vec<FixtureLog>,
    end: HashMap<String, State>,
}

#[derive(Deserialize)]
struct FixturePool {
    id: String,
    currency0: String,
    currency1: String,
}

#[derive(Deserialize, Clone, Default, Debug, PartialEq)]
struct State {
    attributes: BTreeMap<String, String>,
}

#[derive(Deserialize)]
struct FixtureLog {
    block_number: u64,
    transaction_hash: String,
    transaction_index: u32,
    log_index: u32,
    address: String,
    topics: Vec<String>,
    data: String,
}

fn unhex(value: &str) -> Vec<u8> {
    hex::decode(value.trim_start_matches("0x")).expect("fixture hex")
}

/// Pool attributes with every value decoded, a missing value counting as zero.
#[derive(Default, Debug, PartialEq)]
struct Values(BTreeMap<String, BigInt>);

impl Values {
    fn from_state(state: &State) -> Self {
        Self(
            state
                .attributes
                .iter()
                .map(|(name, value)| (name.clone(), BigInt::from_signed_bytes_be(&unhex(value))))
                .filter(|(_, value)| !value.is_zero())
                .collect(),
        )
    }

    /// Applies one transaction's output as the indexer resolves it.
    fn apply(&mut self, entity: &EntityChanges) {
        for attr in &entity.attributes {
            let value = BigInt::from_signed_bytes_be(&attr.value);
            let current = self
                .0
                .entry(attr.name.clone())
                .or_insert_with(BigInt::zero);
            match attr.change() {
                ChangeType::Delta => *current = current.clone() + value,
                ChangeType::Update | ChangeType::Creation => *current = value,
                ChangeType::Deletion => *current = BigInt::zero(),
                ChangeType::Unspecified => panic!("unspecified change on {}", attr.name),
            }
        }
        self.0
            .retain(|_, value| !value.is_zero());
    }
}

fn run_case(case: &Case) {
    // The stores start from the snapshot the indexer passes; pools created in the stream would
    // come from `map_pools_created`, which a replay from creation emulates with the fixture list.
    let snapshot = snapshot_pools(&case.snapshot_params, case.start_block + 1).unwrap();
    let mut pools: HashMap<String, Pool> = HashMap::new();
    let mut ticks: HashMap<String, i64> = HashMap::new();
    let mut prices: HashMap<String, BigInt> = HashMap::new();
    for seeded in snapshot.pools {
        let key = seeded.store_key();
        ticks.insert(key.clone(), seeded.tick.into());
        prices.insert(key.clone(), seeded.sqrt_price_x96.parse().unwrap());
        pools.insert(key, seeded.pool.unwrap());
    }
    if case.snapshot_params.is_empty() {
        for p in &case.pools {
            let pool = Pool {
                id: unhex(&p.id),
                currency0: unhex(&p.currency0),
                currency1: unhex(&p.currency1),
                created_tx_hash: vec![],
            };
            pools.insert(format!("pool:{}", p.id), pool);
        }
    }
    assert_eq!(pools.len(), case.pools.len(), "case {}: snapshot pools", case.name);
    let mut state: HashMap<String, Values> = case
        .start
        .iter()
        .map(|(pool, state)| (pool.clone(), Values::from_state(state)))
        .collect();

    let mut blocks: BTreeMap<u64, Vec<&FixtureLog>> = BTreeMap::new();
    for log in &case.logs {
        blocks
            .entry(log.block_number)
            .or_default()
            .push(log);
    }
    for (_, mut logs) in blocks {
        logs.sort_by_key(|log| log.log_index);
        let pool_events: Vec<PoolEvent> = logs
            .iter()
            .filter_map(|log| {
                let eth_log = Log {
                    address: unhex(&log.address),
                    topics: log
                        .topics
                        .iter()
                        .map(|t| unhex(t))
                        .collect(),
                    data: unhex(&log.data),
                    index: log.log_index,
                    block_index: log.log_index,
                    ordinal: u64::from(log.log_index),
                };
                let tx = TransactionTrace {
                    hash: unhex(&log.transaction_hash),
                    index: log.transaction_index,
                    ..Default::default()
                };
                log_to_event(&eth_log, &tx, |key| pools.get(&key).cloned())
            })
            .collect();

        // The tick and price stores answer with the value set by an earlier event of the stream.
        let mut before: HashMap<u64, (Option<i64>, Option<BigInt>)> = HashMap::new();
        for event in &pool_events {
            let key = format!("pool:{}", event.pool_id);
            before.insert(event.log_ordinal, (ticks.get(&key).copied(), prices.get(&key).cloned()));
            if let Some((pool, _, tick)) = event_to_current_tick(event.clone()) {
                ticks.insert(format!("pool:{pool}"), tick.into());
            }
            if let Some((pool, _, price)) = event_to_current_sqrt_price(event.clone()) {
                prices.insert(format!("pool:{pool}"), price);
            }
        }
        let events = Events { pool_events };
        let liquidity =
            liquidity_changes(events.clone(), |event| before[&event.log_ordinal].0).unwrap();
        let balances =
            balance_changes(events.clone(), |event| before[&event.log_ordinal].1.clone()).unwrap();
        let changes = collect_transaction_changes(
            BlockEntityChanges::default(),
            events.clone(),
            balances,
            TickDeltas {
                deltas: events
                    .pool_events
                    .iter()
                    .cloned()
                    .flat_map(event_to_ticks_deltas)
                    .collect(),
            },
            liquidity,
        );
        for tx in changes {
            for entity in &tx.entity_changes {
                state
                    .entry(entity.component_id.clone())
                    .or_default()
                    .apply(entity);
            }
        }
    }

    for (pool, expected) in &case.end {
        let got = state.remove(pool).unwrap_or_default();
        assert_eq!(got, Values::from_state(expected), "case {}: pool {pool}", case.name);
    }
}

#[test]
fn test_replay_matches_chain() {
    let fixture: Fixture =
        serde_json::from_str(include_str!("../../tests/fixtures/replay.json")).unwrap();
    let names: Vec<&str> = fixture
        .cases
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(names, ["bootstrap", "replay"]);
    for case in &fixture.cases {
        run_case(case);
    }
}

#[test]
fn test_liquidity_change_without_tick_fails() {
    use crate::pb::uniswap::v4::events::pool_event::{ModifyLiquidity, Type};
    let event = PoolEvent {
        log_ordinal: 1,
        pool_id: "0xaa".to_string(),
        currency0: "0x01".to_string(),
        currency1: "0x02".to_string(),
        transaction: Some(Default::default()),
        r#type: Some(Type::ModifyLiquidity(ModifyLiquidity {
            sender: String::new(),
            tick_lower: -10,
            tick_upper: 10,
            liquidity_delta: "5".to_string(),
            salt: String::new(),
        })),
    };
    let events = Events { pool_events: vec![event] };
    assert!(liquidity_changes(events.clone(), |_| None).is_err());
    assert!(balance_changes(events.clone(), |_| None).is_err());
    let changes = liquidity_changes(events, |_| Some(0)).unwrap();
    assert_eq!(changes.changes.len(), 1);
}
